# Generated by Django 3.1.1 on 2020-10-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('home_number', models.IntegerField(verbose_name='Номер дома')),
                ('home_sub_number', models.CharField(blank=True, default=0, help_text='Если отсутствует,                                        ставьте ноль', max_length=2, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Адрес дома',
                'verbose_name_plural': 'Адреса домов',
                'ordering': ['adress', 'home_number'],
                'unique_together': {('adress', 'home_number', 'home_sub_number')},
            },
        ),
        migrations.CreateModel(
            name='HomeParametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOP', models.DecimalField(decimal_places=2, help_text='метры квадратные', max_digits=5, verbose_name='Площадь мест общего пользования')),
                ('norm_cold_water', models.DecimalField(decimal_places=2, help_text='тонн на метр квадратный', max_digits=3, verbose_name='Норматив горячего                                           водоснабжения')),
                ('norm_hot_water', models.DecimalField(decimal_places=2, help_text='тонн на метр квадратный', max_digits=3, verbose_name='Норматив холодного                                          водоснабжения')),
                ('norm_heating', models.DecimalField(decimal_places=4, help_text='Гкал на метр квадратный', max_digits=5, verbose_name='Норматив отопления или                                        подогрев')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Параметры дома',
                'verbose_name_plural': 'Параметры домов',
                'ordering': ['home'],
                'unique_together': {('home', 'MOP')},
            },
        ),
        migrations.CreateModel(
            name='HomeApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер помещения')),
                ('apartment_type', models.CharField(choices=[('residential', 'Жилое'), ('non-residential', 'Нежилое')], default='residential', max_length=15, verbose_name='Тип помещения')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Перечень помещений',
                'verbose_name_plural': 'Перечень помещений',
                'ordering': ['home', 'number'],
                'unique_together': {('home', 'number')},
            },
        ),
    ]
