# Generated by Django 3.1.2 on 2020-10-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('time_record', models.DateField(verbose_name='Дата')),
                ('resource_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('heating', 'Отопление'), ('drainage', 'Водоотведение'), ('electricity', 'Электричество')], default='heating', max_length=15, verbose_name='Тип коммунального ресурса')),
                ('norm_mass', models.DecimalField(decimal_places=3, help_text='тонн на кв.м.', max_digits=6, verbose_name='Норматив, тонны')),
                ('norm_finance', models.DecimalField(blank=True, decimal_places=2, help_text='рублей', max_digits=7, null=True, verbose_name='Норматив, руб.')),
                ('over_in_weight', models.DecimalField(blank=True, decimal_places=3, help_text='тонны', max_digits=6, null=True, verbose_name='Перерасход, тонны')),
                ('over_in_finance', models.DecimalField(blank=True, decimal_places=2, help_text='рублей', max_digits=7, null=True, verbose_name='Перерасход, рублей')),
                ('accrued_mass', models.DecimalField(blank=True, decimal_places=3, help_text='тонны', max_digits=6, null=True, verbose_name='Начислено населению, тонны')),
                ('accured_finance', models.DecimalField(blank=True, decimal_places=2, help_text='рублей', max_digits=7, null=True, verbose_name='Начисленно населению, руб.')),
                ('saldo_mass', models.DecimalField(blank=True, decimal_places=3, help_text='тонны', max_digits=6, null=True, verbose_name='Сальдо, тонны')),
                ('saldo_finance', models.DecimalField(blank=True, decimal_places=2, help_text='рублей', max_digits=7, null=True, verbose_name='Сальдо, руб.')),
                ('payed', models.DecimalField(blank=True, decimal_places=3, help_text='рублей', max_digits=6, null=True, verbose_name='Оплачено населением, руб.')),
                ('tarif', models.DecimalField(decimal_places=2, help_text='рублей за тонну', max_digits=5, verbose_name='Тариф')),
                ('nalog', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Налог')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Расчёт ресурсов',
                'verbose_name_plural': 'Расчёт ресурсов',
                'ordering': ['home', 'time_record'],
                'unique_together': {('home', 'time_record')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('time_record', models.DateField(verbose_name='Дата')),
                ('resource_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('heating', 'Отопление'), ('drainage', 'Водоотведение'), ('electricity', 'Электричество')], default='heating', max_length=15, verbose_name='Тип коммунального ресурса')),
                ('ODPU_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Расход по ОДПУ, тонны')),
                ('ODPU_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Расход по ОДПУ, Гкал')),
                ('IPU_RP_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Расход по ИПУ (жилые пом.), тонны')),
                ('IPU_RP_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Расход по ИПУ (жилые пом.), Гкал')),
                ('IPU_nonRP_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Расхо по ИПУ (нежил. пом.), тонны')),
                ('IPU_nonRP_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Расход по ИПУ (неж. пом), Гкал')),
                ('ODN_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Расход по ОДН, тонны')),
                ('ODN_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Расход по ОДН, Гкал')),
                ('negative_ODN_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Отрицательный ОДН, тонны')),
                ('negative_ODN_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Отрицательный ОДН, Гкал')),
                ('result_ODN_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='Итоговый ОДН, тонны')),
                ('result_ODN_calories', models.DecimalField(decimal_places=5, help_text='Гкал', max_digits=9, verbose_name='Итоговый ОДН, Гкал')),
                ('payable_ODN_mass', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=8, verbose_name='ОДН к начислению, тонный')),
                ('payable_ODN_calories', models.DecimalField(decimal_places=5, help_text='тонн', max_digits=9, verbose_name='ОДН к начислению, Гкал')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Показания РСО',
                'verbose_name_plural': 'Показания РСО',
                'ordering': ['home'],
                'unique_together': {('home', 'time_record')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionODPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('heating', 'Отопление'), ('drainage', 'Водоотведение'), ('electricity', 'Электричество')], default='heating', max_length=15, verbose_name='Тип коммунального ресурса')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('time_record', models.DateField(blank=True, help_text='Если оставить пустым,                                    автоматически установится 18                                    число текущего месяца \n', null=True, verbose_name='Дата снятия показаний')),
                ('temp1', models.DecimalField(decimal_places=2, default=0, help_text='Если не заполнено                                 значение поля = 0', max_digits=6, verbose_name='T1, градусы Цельсия')),
                ('temp2', models.DecimalField(decimal_places=2, default=0, help_text='Если не заполнено                                 значение поля = 0', max_digits=6, verbose_name='T2, градусы Цельсия')),
                ('G1', models.DecimalField(decimal_places=2, default=0, help_text='Если не заполнено                              значение поля = 0', max_digits=5, verbose_name='G1, тонны в час')),
                ('G2', models.DecimalField(decimal_places=2, default=0, help_text='Если не заполнено                              значение поля = 0', max_digits=5, verbose_name='G2, тонны в час')),
                ('work_time', models.IntegerField(help_text='Время работы счёта', verbose_name='Tуч, время учёта')),
                ('idle_time', models.IntegerField(help_text='Время работы прибора', verbose_name='Tнар, время наработки')),
                ('Q1', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Q1, Гкал')),
                ('M1', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='M1, тонны')),
                ('M2', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='M1, тонны')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Показания ОДПУ',
                'verbose_name_plural': 'Показания ОДПУ',
                'ordering': ['home', 'time_record'],
                'unique_together': {('home', 'resource_type', 'time_record')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionHomeIPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('time_record', models.DateField(blank=True, help_text='Если оставить пустым,                                    автоматически установится 18                                    число текущего месяца \n', null=True, verbose_name='Дата снятия показаний')),
                ('resource_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('heating', 'Отопление'), ('drainage', 'Водоотведение'), ('electricity', 'Электричество')], default='heating', max_length=15, verbose_name='Тип коммунального ресурса')),
                ('IPU_mass', models.DecimalField(decimal_places=2, default=0, help_text='тонны', max_digits=7, verbose_name='Расход по ИПУ, тонны')),
                ('IPU_calories', models.DecimalField(decimal_places=6, default=0, help_text='Если оставить пустым,                                        поле автоматически заполнится', max_digits=8, verbose_name='Расход по ИПУ, Гкал')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Суммарные показания ИПУ',
                'verbose_name_plural': 'Суммарные показания ИПУ',
                'ordering': ['home', 'resource_type'],
                'unique_together': {('home', 'time_record', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionApartmentIPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('time_record', models.DateField(blank=True, help_text='Если оставить пустым,                                    автоматически установится 18                                    число текущего месяца \n', null=True, verbose_name='Дата снятия показаний')),
                ('resource_type', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('heating', 'Отопление'), ('drainage', 'Водоотведение'), ('electricity', 'Электричество')], default='heating', max_length=15, verbose_name='Тип коммунального ресурса')),
                ('IPU_indication', models.DecimalField(decimal_places=2, default=0, help_text='тонны', max_digits=7, verbose_name='Показание ИПУ, тонны')),
                ('IPU_consumption', models.DecimalField(decimal_places=2, default=0, help_text='тонны', max_digits=7, verbose_name='Расход по ИПУ, тонны')),
                ('IPU_calories', models.DecimalField(decimal_places=4, default=0, help_text='Гкал', max_digits=7, verbose_name='Расход по ИПУ, Гкал')),
                ('recalculation_mass', models.DecimalField(decimal_places=3, default=0, help_text='тонны', max_digits=7, verbose_name='Перерасчёт, тонны')),
                ('recalculation_calories', models.DecimalField(decimal_places=3, default=0, help_text='Гкал', max_digits=7, verbose_name='Перерасчёт, Гкал')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.homeapartment', verbose_name='Помещение')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Показания ИПУ в помещениях',
                'verbose_name_plural': 'Показания ИПУ в помещениях',
                'ordering': ['home', 'apartment'],
                'unique_together': {('home', 'apartment', 'time_record', 'resource_type')},
            },
        ),
    ]
