# Generated by Django 3.1.1 on 2020-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeparametrs',
            name='nor_heating',
        ),
        migrations.AddField(
            model_name='homeparametrs',
            name='norm_heating',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Гкал на метр квадратный', max_digits=5, verbose_name='Норматив отопления или                                        подогрев'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeparametrs',
            name='norm_cold_water',
            field=models.DecimalField(decimal_places=2, help_text='тонн на метр квадратный', max_digits=3, verbose_name='Норматив горячего                                           водоснабжения'),
        ),
        migrations.AlterField(
            model_name='homeparametrs',
            name='norm_hot_water',
            field=models.DecimalField(decimal_places=2, help_text='тонн на метр квадратный', max_digits=3, verbose_name='Норматив холодного                                          водоснабжения'),
        ),
    ]
