# Generated by Django 3.1.1 on 2020-09-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0002_auto_20200920_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionipu',
            options={'verbose_name': 'Показания ИПУ', 'verbose_name_plural': 'Показаний ИПУ'},
        ),
        migrations.AlterModelOptions(
            name='consumptionodpu',
            options={'ordering': ['time_record'], 'verbose_name': 'Показания ОДПУ', 'verbose_name_plural': 'Показаний ОДПУ'},
        ),
        migrations.AlterModelOptions(
            name='consumptionrso',
            options={'verbose_name': 'Показания РСО', 'verbose_name_plural': 'Показаний РСО'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['adress', 'home_number'], 'verbose_name': 'Дома', 'verbose_name_plural': 'Домов'},
        ),
        migrations.AlterModelOptions(
            name='homeapartment',
            options={'ordering': ['number'], 'verbose_name': 'Помещения', 'verbose_name_plural': 'Помещений'},
        ),
        migrations.AlterModelOptions(
            name='homeparametrs',
            options={'verbose_name': 'Параметры дома', 'verbose_name_plural': 'Параметры домов'},
        ),
        migrations.AlterModelOptions(
            name='resourcecharge',
            options={'ordering': ['time_record'], 'verbose_name': 'Рассчёт ресурсов', 'verbose_name_plural': 'Рассчёты ресурсов'},
        ),
    ]
