# Generated by Django 3.1.1 on 2020-09-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0003_auto_20200920_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionrso',
            options={'verbose_name': 'Показания РСО', 'verbose_name_plural': 'Показания РСО'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['adress', 'home_number'], 'verbose_name': 'Адреса дома', 'verbose_name_plural': 'Адреса домов'},
        ),
        migrations.AlterModelOptions(
            name='homeapartment',
            options={'ordering': ['number'], 'verbose_name': 'Перечень помещений', 'verbose_name_plural': 'Перечень помещений'},
        ),
        migrations.AlterModelOptions(
            name='resourcecharge',
            options={'ordering': ['time_record'], 'verbose_name': 'Рассчёт ресурсов', 'verbose_name_plural': 'Рассчёт ресурсов'},
        ),
    ]
