# Generated by Django 3.1.1 on 2020-09-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0004_auto_20200920_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionipu',
            options={'verbose_name': 'Показания ИПУ', 'verbose_name_plural': 'Показания ИПУ'},
        ),
        migrations.AlterModelOptions(
            name='consumptionodpu',
            options={'ordering': ['time_record'], 'verbose_name': 'Показания ОДПУ', 'verbose_name_plural': 'Показания ОДПУ'},
        ),
    ]
