# Generated by Django 3.1.1 on 2020-09-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0005_auto_20200920_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['adress', 'home_number'], 'verbose_name': 'Адрес дома', 'verbose_name_plural': 'Адреса домов'},
        ),
    ]
