# Generated by Django 3.1.1 on 2020-09-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0006_auto_20200920_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeapartment',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
    ]
