# Generated by Django 3.1.1 on 2020-09-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0007_auto_20200920_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionipu',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='consumptionodpu',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='consumptionrso',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='homeparametrs',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='resourcecharge',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat.home', verbose_name='Адрес'),
        ),
    ]
