# Generated by Django 3.1.2 on 2020-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0009_auto_20200920_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionipu',
            options={'ordering': ['home', 'apartment'], 'verbose_name': 'Показания ИПУ', 'verbose_name_plural': 'Показания ИПУ'},
        ),
        migrations.AlterModelOptions(
            name='consumptionodpu',
            options={'ordering': ['home', 'time_record'], 'verbose_name': 'Показания ОДПУ', 'verbose_name_plural': 'Показания ОДПУ'},
        ),
        migrations.AlterModelOptions(
            name='consumptionrso',
            options={'ordering': ['home'], 'verbose_name': 'Показания РСО', 'verbose_name_plural': 'Показания РСО'},
        ),
        migrations.AlterModelOptions(
            name='homeapartment',
            options={'ordering': ['home', 'number'], 'verbose_name': 'Перечень помещений', 'verbose_name_plural': 'Перечень помещений'},
        ),
        migrations.AlterModelOptions(
            name='homeparametrs',
            options={'ordering': ['home'], 'verbose_name': 'Параметры дома', 'verbose_name_plural': 'Параметры домов'},
        ),
        migrations.AlterModelOptions(
            name='resourcecharge',
            options={'ordering': ['home', 'time_record'], 'verbose_name': 'Расчёт ресурсов', 'verbose_name_plural': 'Расчёт ресурсов'},
        ),
        migrations.AlterField(
            model_name='home',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.IntegerField(max_length=3, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='homeapartment',
            name='number',
            field=models.IntegerField(max_length=4, verbose_name='Номер помещения'),
        ),
        migrations.AlterUniqueTogether(
            name='consumptionipu',
            unique_together={('home', 'apartment', 'time_record')},
        ),
        migrations.AlterUniqueTogether(
            name='consumptionodpu',
            unique_together={('home', 'resource_type', 'time_record')},
        ),
        migrations.AlterUniqueTogether(
            name='consumptionrso',
            unique_together={('home', 'time_record')},
        ),
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('adress', 'home_number', 'home_sub_number')},
        ),
        migrations.AlterUniqueTogether(
            name='homeapartment',
            unique_together={('home', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='homeparametrs',
            unique_together={('home', 'MOP')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcecharge',
            unique_together={('home', 'time_record')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='consumptionipu',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='consumptionrso',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='homeparametrs',
            order_with_respect_to=None,
        ),
    ]
