# Generated by Django 3.1.2 on 2020-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat', '0010_auto_20201001_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='homeapartment',
            name='number',
            field=models.IntegerField(verbose_name='Номер помещения'),
        ),
    ]
