# Generated by Django 3.1.1 on 2020-10-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasport', '0001_initial'),
        ('heat', '0011_auto_20201001_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeapartment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='homeapartment',
            name='home',
        ),
        migrations.AlterUniqueTogether(
            name='homeparametrs',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='homeparametrs',
            name='home',
        ),
        migrations.AlterField(
            model_name='consumptionipu',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.homeapartment'),
        ),
        migrations.AlterField(
            model_name='consumptionipu',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='consumptionodpu',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='consumptionrso',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='resourcecharge',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasport.home', verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='HomeApartment',
        ),
        migrations.DeleteModel(
            name='HomeParametrs',
        ),
    ]
